### PR TITLE
Event handling and element creation on fleek

### PR DESCRIPTION
**Pull request by SaulDoesCode**
it's a bit longer but there's a lot of nice new functionality, also fixed some things that would not have worked in evergreen browsers namely ``function (param = 'default') {}`` here and there. Some changes were just formatting, making lines longer than 80 chars shorter.

Event handling is now officially on fleek in this project, so there's that.

I would recommend however that .createObject be renamed to something else because Object.create exists and there might be some unwanted ambiguity, consider perhaps .createElement, .el, .dom or .makeNode you know, something like that.

Anyway you can always change what you don't like, maybe remove some things that are just too extra.
All in all interesting project, had fun contributing.

### CODE REVIEW

**Comment by Norair1997** [comment]
Wow! Thank you!
I am just going through your code and try to understand what you're doing :)
Keep in mind that I want not to get too much big.

And i want to change the syntax of the event function...
nor.event( [likeBefore], {'click': clickFunction, 'mouseenter': mouseFunction});
"It seems much more natural that way, in my opinion, instead of having to keep track of the order in which you add the events." <--- feedback from a reddit user...Which I really like

**Comment by SaulDoesCode** [comment]
Yeah sorry that it's a bit big, maybe limit what options there should be for event handling to only strings/objects. The lines of code don't matter as much as the density, much of it is not so dense so it should still be pretty small when minified and compressed.

Maybe you could keep adding things to ``nor`` to make it a full framework? Even then it still won't be as huge and heavy as angular or something.

So many frameworks add a whole lot of nothing like AbstractObjectFactories and Providers, when you really look at the code and think what do I need to build my app it's really not that much. I like libraries that does one or two things really well and plays nice with other libraries, react does not mix well with say a vanilla scroll-bar plugin or web-component; and then you think about how massive react is when all it does is add Component wrappers with vdom diffing and lifecycle hooks. You can achieve everything React does with Jquery or dare I say vanilla.js by using a consistent coding methodology or creative strategy.

Perhaps with nor you could flesh it out like mithril or hyperapp and add things that other frameworks don't have. Could make for a nice portfolio project.

Sorry just rambling but yeah it's a cool project think about what you want it to become.

**Comment by SaulDoesCode** [comment]
OK so the event handler will no longer accept
```js
nor.event('.selector', ['x', 'y'], [x => {}, y => {}])
```
for multi-event-listeners,
it will now accept
```js
nor.event('.selector', {
   x: e => {},
   click (e, element) {
      element.classList.toggle('open');
   }
})
```

the whole thing is a bit smaller now, I had to add a ``.dupeObj`` function for object listeners with array targets as the manager object get's overridden if each target uses the same object.

**Comment by Norair1997** [comment]
Thank you! 
I don't have much time during the week to work on it. Just in the weekends. 
```
nor.event('.selector', {
   x: e => {},
   click (e, element) {
      element.classList.toggle('open');
   }
})

I can't have multiple selectors anymmore?
nor.event(['.selector', '#idFoo', someHTMLObject], {
   x: e => {},
   click (e, element) {
      element.classList.toggle('open');
   }
})
// sorry and what do you mean with
//   x: e => {}, 
// x ?= trigger?   and e paramter and {} function?
```

**Comment by SaulDoesCode** [comment]
``e => {}`` is the same as ``function(e) {}`` it's called an arrow function it's part of ES6 (newer javascript post-2015), it's the same thing as a lambda if you're coming from the C#/Java world.

> I can't have multiple selectors anymore?

You can have multiple selectors it works fine.
```js
nor.event(['.selector', '#idFoo', someHTMLObject], {
   x: e => {}, // <- same as { "x": function (e) {} }
   click (e, element) {
      element.classList.toggle('open');
   }
})
```
What I meant was you can't have ``[a, b, c] = [fn1, fn2, fn3]`` anymore.

You can even have nested arrays as selectors
```html
	<button class="btn">1</button>
	<button class="btn">2</button>
	<button class="btn">3</button>
	
	<input type="submit" name="funny btn" value="4">
```

```js
 nor.on(['.btn', 'input[type="submit"]'], 'click', (e, btn) => {
	console.log(`You clicked button #${btn.textContent || btn.value}`)
 })
```

**Comment by SaulDoesCode** [comment]
I saw on reddit someone talking about converting this project to ES6/ESNEXT you know anything above ye olde ES5. Should we try to convert all this to ES6 you think and set up babel and a proper package.json?

**Comment by SaulDoesCode** [comment]
Awesome

**Pull request merged**
